[package]
name = "helium-config-service-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.0"
tonic = "0.8.2"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
serde = {version = "1.0.145", features = ["derive"]}
serde_json = "1.0.87"
serde-hex = "0.1.0"
clap = { version = "4.0.18", features = ["derive"] }
config = { version = "0.13.2", default-features=false, features = ["toml"] }
helium-proto = { git = "https://github.com/helium/proto", branch="master", features=["services"]}
dialoguer = "0.10.2"
toml = "0.5.9"
anyhow = "1.0.66"
