[package]
name = "helium-config-service-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.0"
tonic = { version = "0.8.2", features = ["tls", "tls-roots"] }
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.87"
clap = { version = "4.1.4", features = ["derive", "env"] }
helium-proto = { git = "https://github.com/helium/proto", branch="jg/skfs-as-hex", features=["services"]}
helium-crypto = "0.6.6"
dialoguer = "0.10.2"
anyhow = "1.0.68"
serde_test = "1.0.147"
rand = "0.8.5"
ipnet = "2.5.1"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tokio-stream = "0.1.11"
futures = "0.3.25"

[dev-dependencies]
pretty_assertions = "1.3.0"
temp-dir = "0.1.11"
